#!/usr/bin/env bash
# Generate a markdown report for an io500 results directory.
#
# Usage:
#   scripts/generate-report.sh [--no-claude] <results-dir>
#
# Example:
#   scripts/generate-report.sh results/20260518T152012Z-pre-maint
#   scripts/generate-report.sh --no-claude results/20260518T152012Z-pre-maint
#
# What it writes:
#   <results-dir>/report-<benchmark-timestamp>-<label>.md
#
# The report has three sections:
#   1. Header (label, timestamp, nodes/ranks, slurm job, config path)
#   2. Results table (parsed from result_summary.txt) + final [SCORE] line
#   3. Run Analysis + Suggested Improvements. Source for (3):
#        - If `claude` is on PATH and --no-claude was not passed: generated
#          by `claude -p` from result_summary.txt + run-metadata.txt +
#          config-used.ini.
#        - Else: generated by scripts/generate-report.py (rule-based
#          heuristics + matplotlib chart + cross-run comparison). The
#          Python path runs inside the project's pixi env (pixi.toml at
#          the repo root); if pixi is missing it falls back to plain
#          python3 with charts disabled.

set -euo pipefail

USE_CLAUDE=auto
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-claude) USE_CLAUDE=no; shift ;;
    --with-claude) USE_CLAUDE=yes; shift ;;  # force, error if missing
    -h|--help)
      sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    --) shift; break ;;
    -*) echo "ERROR: unknown flag: $1" >&2; exit 2 ;;
    *)  break ;;
  esac
done

DIR="${1:-}"
if [[ -z "$DIR" ]]; then
  echo "usage: $0 [--no-claude] <results-dir>" >&2
  exit 2
fi
DIR="$(readlink -f -- "$DIR")"

SCRIPT_DIR="$(cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PY_SCRIPT="$SCRIPT_DIR/generate-report.py"
PIXI_MANIFEST="$REPO_ROOT/pixi.toml"

for f in result_summary.txt run-metadata.txt; do
  if [[ ! -f "$DIR/$f" ]]; then
    echo "ERROR: $DIR is missing $f -- doesn't look like an io500 results dir" >&2
    exit 1
  fi
done

# Pull a single value out of run-metadata.txt by key.
meta() { sed -n "s|^$1:[[:space:]]*||p" "$DIR/run-metadata.txt"; }

TS="$(meta timestamp_utc)"
LABEL="$(meta label)"
JOB="$(meta slurm_job_id)"
NODES="$(meta slurm_nnodes)"
NODELIST="$(meta slurm_nodelist)"
RANKS="$(meta slurm_ntasks)"
RPN="$(meta slurm_ntasks_per_node)"
CONFIG="$(meta config)"
HOST="$(meta host)"

if [[ -z "$TS" || -z "$LABEL" ]]; then
  echo "ERROR: couldn't parse timestamp/label from $DIR/run-metadata.txt" >&2
  exit 1
fi

REPORT="$DIR/report-${TS}-${LABEL}.md"

# --- Section 1 + 2: deterministic header + results table ---------------------
{
  echo "# IO500 Run Report — \`$LABEL\`"
  echo
  echo "| Field | Value |"
  echo "|---|---|"
  echo "| Benchmark timestamp (UTC) | \`$TS\` |"
  echo "| Label | \`$LABEL\` |"
  echo "| Config | \`$CONFIG\` |"
  echo "| Slurm job | \`$JOB\` |"
  echo "| Launch host | \`$HOST\` |"
  echo "| Nodes | $NODES (\`$NODELIST\`) |"
  echo "| Ranks | $RANKS ($RPN per node) |"
  echo
  echo "## Phase Results"
  echo
  # Render as a Unicode box-drawing table inside a fenced code block.
  # Code-fenced so the markdown renderer uses a monospace font and the
  # borders align. Column widths are computed from the longest cell.
  echo '```'
  awk '
    BEGIN {
      hdr[1]="Phase"; hdr[2]="Score"; hdr[3]="Time"
      for (j=1; j<=3; j++) w[j] = length(hdr[j])
      n=0
    }
    /^\[RESULT\]/ {
      # Format: [RESULT] <phase> <value> <unit> : time <elapsed> seconds
      n++
      rows[n,1] = $2
      rows[n,2] = $3 " " $4
      rows[n,3] = $7 " s"
      for (j=1; j<=3; j++) if (length(rows[n,j]) > w[j]) w[j] = length(rows[n,j])
    }
    function dashes(k,    s, i) { s=""; for (i=0;i<k;i++) s=s"─"; return s }
    function border(L, M, R,    line, j) {
      line = L
      for (j=1; j<=3; j++) line = line dashes(w[j]+2) ((j<3) ? M : R)
      print line
    }
    END {
      if (n == 0) { print "(no [RESULT] phases found in result_summary.txt)"; exit }
      border("┌","┬","┐")
      printf "│ %-*s │ %-*s │ %-*s │\n", w[1], hdr[1], w[2], hdr[2], w[3], hdr[3]
      border("├","┼","┤")
      for (i=1; i<=n; i++)
        printf "│ %-*s │ %-*s │ %-*s │\n", w[1], rows[i,1], w[2], rows[i,2], w[3], rows[i,3]
      border("└","┴","┘")
    }
  ' "$DIR/result_summary.txt"
  echo '```'
  echo

  SCORE_LINE="$(grep -E '^\[SCORE' "$DIR/result_summary.txt" || true)"
  if [[ -n "$SCORE_LINE" ]]; then
    echo "**Final:** \`$SCORE_LINE\`"
  else
    echo "_No \`[SCORE]\` line found in result_summary.txt — the run may have been killed before completion._"
  fi
  echo
} > "$REPORT"

# --- Section 3: AI-generated analysis + suggestions --------------------------
if ! command -v claude >/dev/null 2>&1; then
  cat >> "$REPORT" <<'EOF'
## Run Analysis

_The `claude` CLI was not on PATH when this report was generated. Fill
this section in manually, or install Claude Code and re-run
`scripts/generate-report.sh` against this directory._

## Suggested Improvements

_(See above.)_
EOF
  echo "WARNING: claude CLI not found; analysis sections left as stub" >&2
  echo "Report written: $REPORT"
  exit 0
fi

# Build the context Claude sees. Keep it bounded -- these files are all
# small (~few KB each), so just inline them.
CONFIG_USED="$DIR/config-used.ini"
[[ -f "$CONFIG_USED" ]] || CONFIG_USED=/dev/null

PROMPT=$(cat <<EOF
You are analyzing a single IO500 benchmark run on the ASU BeeGFS scratch
array (/scratch/acchapm1/io, 3.7 PB). Below are the result_summary, run
metadata, and the config used.

Write exactly TWO markdown sections, in this order, with no other
preamble, commentary, or closing remarks:

## Run Analysis

2-3 short paragraphs (prose, not bullets). Briefly identify what the
phases collectively measure (bandwidth vs. metadata, easy vs. hard
patterns, the find phase) without lecturing about every individual
phase. Then focus on what is notable about THIS run specifically:
which phases dominated the time, which scored well vs. poorly relative
to expectations for a parallel filesystem at this node count, any
[INVALID] markers, and what the final TOTAL score reflects.

## Suggested Improvements

A bulleted list of 4-6 specific, actionable suggestions ordered by
expected impact (highest first). Each bullet must:
  - Name a specific config knob (e.g. \`[ior-hard] segmentCount\`,
    \`[mdtest-easy] n\`, \`stonewall-time\`) OR a concrete system-level
    change (e.g. "raise BeeGFS metadata target count", "enable
    \`drop-caches\` between phases", "add more storage targets").
  - In one sentence, explain why it might help, anchored to a number
    or pattern from THIS run's results -- not a generic platitude.

Avoid generic advice ("use more nodes", "tune the filesystem"). Be
concrete enough that the reader can act on each bullet without further
research. Do not suggest changes that would invalidate the IO500
score (e.g. lowering stonewall-time below 300, unless explicitly
flagging that the suggestion is for development only).

=== result_summary.txt ===
$(cat "$DIR/result_summary.txt")

=== run-metadata.txt ===
$(cat "$DIR/run-metadata.txt")

=== config-used.ini ===
$(cat "$CONFIG_USED")
EOF
)

echo "Calling claude -p (this may take ~30-60s)..."
if ! claude -p "$PROMPT" >> "$REPORT" 2>/tmp/claude-err.$$; then
  echo "ERROR: claude -p failed; see /tmp/claude-err.$$" >&2
  cat >> "$REPORT" <<EOF

## Run Analysis

_\`claude -p\` failed during report generation. Fill in manually._

## Suggested Improvements

_(See above.)_
EOF
fi

echo
echo "Report written: $REPORT"
